apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-tailscale
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - vault
  rules:
    - host: vault
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault-ui
                port:
                  number: 8200
