apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: homelab
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: keycloak
      targetRevision: "*"
      helm:
        releaseName: keycloak
        valueFiles:
          - $values/infrastructure/keycloak/values.yaml
    - repoURL: https://github.com/rexdivakar/homelab-gitops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/rexdivakar/homelab-gitops.git
      targetRevision: HEAD
      path: infrastructure/keycloak
      directory:
        include: keycloak-tailscale-ingress.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
